// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sisso.DAL;

namespace Sisso.DAL.Migrations
{
    [DbContext(typeof(SissoContext))]
    partial class SissoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sisso.BE.Entities.Persona", b =>
                {
                    b.Property<Guid>("PersonaId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApellidoMaterno");

                    b.Property<string>("ApellidoPaterno");

                    b.Property<DateTime>("Created");

                    b.Property<DateTime?>("Deleted");

                    b.Property<DateTime>("Modified");

                    b.Property<string>("NroDoi");

                    b.Property<string>("PrimerNombre");

                    b.Property<string>("SegundoNombre");

                    b.Property<byte[]>("TimeStamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("PersonaId");

                    b.ToTable("Personas");

                    b.HasData(
                        new
                        {
                            PersonaId = new Guid("ac902172-aeb3-4285-9e7e-a512a69e69ea"),
                            ApellidoMaterno = "Guarniz",
                            ApellidoPaterno = "Saavedra",
                            Created = new DateTime(2019, 7, 13, 16, 25, 57, 42, DateTimeKind.Unspecified).AddTicks(6924),
                            Modified = new DateTime(2019, 7, 13, 16, 25, 57, 44, DateTimeKind.Unspecified).AddTicks(4153),
                            NroDoi = "47701560",
                            PrimerNombre = "Oscar",
                            SegundoNombre = "Geny"
                        },
                        new
                        {
                            PersonaId = new Guid("e1725f29-4aea-4fc0-8a55-55a6bf9d96a9"),
                            ApellidoMaterno = "Urteaga",
                            ApellidoPaterno = "Bazan",
                            Created = new DateTime(2019, 7, 13, 16, 25, 57, 45, DateTimeKind.Unspecified).AddTicks(128),
                            Modified = new DateTime(2019, 7, 13, 16, 25, 57, 45, DateTimeKind.Unspecified).AddTicks(161),
                            NroDoi = "87654321",
                            PrimerNombre = "Anderson",
                            SegundoNombre = "Kevin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
